// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LCard: typeof import('./src/components/l-card/index.vue')['default']
    LLayout: typeof import('./src/components/l-layout/index.vue')['default']
    LStatistics: typeof import('./src/components/l-statistics/index.vue')['default']
    LTour: typeof import('./src/components/l-tour/index.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutTour: typeof import('@nutui/nutui-taro')['Tour']
  }
}
